-- Supabase schema for the teacher-facing temporal adverbial annotation app.
-- Run this in Supabase Dashboard -> SQL Editor before deploying the Streamlit app.
--
-- The Streamlit app should use SUPABASE_SERVICE_ROLE_KEY in Streamlit secrets.
-- Do not commit that key to GitHub.

create table if not exists public.annotators (
  annotator_id text primary key,
  display_name text,
  professional_role text,
  experience_years text,
  consent boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.annotations (
  annotation_id bigint generated by default as identity primary key,
  task_id text not null,
  task_type text not null,
  annotator_id text not null references public.annotators(annotator_id) on delete cascade,
  judgement text not null,
  span_correct text,
  role_correct text,
  anchor_correct text,
  usefulness integer,
  confidence integer,
  corrected_span text,
  corrected_role text,
  notes text,
  payload jsonb not null,
  task_json jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(task_id, annotator_id)
);

create index if not exists annotations_annotator_task_type_idx
  on public.annotations (annotator_id, task_type);

create index if not exists annotations_created_at_idx
  on public.annotations (created_at);

-- With a service-role key, Streamlit can write server-side even when RLS is enabled.
-- This prevents public anonymous browser access to the tables.
alter table public.annotators enable row level security;
alter table public.annotations enable row level security;
